RADAR-base/RADAR-Schemas

RADAR-Questionnaire/config.md
REST-API/Heart Rate/README.md
REST-API/Heart Rate/heart-rate.json
REST-API/Heart Rate/heart_rate.avsc
REST-API/Heart Rate/heart_rate_dataset.avsc
REST-API/Heart Rate/heart_rate_item.avsc
REST-API/Heart Rate/heart_rate_value.avsc
REST-API/descriptive_statistic.avsc
REST-API/effective_time_frame.avsc
REST-API/unit.avsc

- descriptive_statistic.avsc is the set of available statical value
- effective_time_frame.avsc describes a time window
- heart_rate_dataset.avsc states a hear rate dataset
- heart_rate_.avsc states a single hear rate sample
- heart_rate_item.avsc is this the dataset item
- heart_rate_value.avsc represents the heart rate double value
- unit.avsc is the set of all available units

New Avro Schemas Heart Rate

---

common/biovotion/biovotion_vsm_acceleration.avsc
common/biovotion/biovotion_vsm_battery_state.avsc
common/biovotion/biovotion_vsm_blood_pulse_wave.avsc
common/biovotion/biovotion_vsm_energy.avsc
common/biovotion/biovotion_vsm_galvanic_skin_response.avsc
common/biovotion/biovotion_vsm_heart_rate.avsc
common/biovotion/biovotion_vsm_heart_rate_variability.avsc
common/biovotion/biovotion_vsm_respiration_rate.avsc
common/biovotion/biovotion_vsm_spo2.avsc
common/biovotion/biovotion_vsm_temperature.avsc

same as #13 but changed source branch (may also do this in base?)
doc changes from #13 still missing

Biovotion schema definitions

---

common/phone/phone_battery_level.avsc
common/phone/phone_call.avsc
common/phone/phone_location.avsc
common/phone/phone_relative_location.avsc
common/phone/phone_sms.avsc
common/phone/phone_user_interaction.avsc

Phone update

---

commons/biovotion/biovotion_vsm_battery_state.avsc
commons/biovotion/biovotion_vsm_led_current.avsc
commons/biovotion/biovotion_vsm_ppg_raw.avsc
commons/biovotion/biovotion_vsm_temperature.avsc

If this is fine I will probably merge both tomorrow...

Biovotion raw schemas

---

commons/phone/phone_call.avsc
commons/phone/phone_gyroscope.avsc
commons/phone/phone_magnetic_field.avsc
commons/phone/phone_sms.avsc
commons/phone/phone_sms_unread.avsc
commons/phone/phone_step_count.avsc
commons/phone/phone_usage_event.avsc

New schemas:
- StepCount
- MagneticField
- Gyroscope
- SmsUnread
Updated schemas:
- Sms
- Call
Needed for the pull requests in RADAR-Android-Phone

New phone sensor and updated sms/call schemas

---

commons/aggregator/phone_usage_aggregator.avsc
commons/phone/phone_usage_total.avsc

Schema for aggregating phone usage events. PR for RADAR-Backend with code using it will come later.

Phone usage aggregates

---

commons/weather/weather_current.avsc
java-sdk/build.gradle

Schema for the [WeatherApi module](https://github.com/RADAR-CNS/RADAR-Android-WeatherApi) with:
- Temperature
- Pressure
- Humidity
- Cloudiness %
- Precipitation of the last 3 hours
- Weather condition (clear, cloudy, rainy, etc..)
- Sunrise
- Sunset

Weather schema

---

Dockerfile
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/service/SourceCatalogueServer.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/AppSource.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/DataProducer.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/active/ActiveSource.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/passive/PassiveSource.java
specifications/active/phq8.yml
specifications/active/thincit.yml
specifications/monitor/radar_prmt.yml
specifications/passive/android_phone.yml
specifications/passive/biovotion_vsm1.yml
specifications/passive/empatica_e4.yml
specifications/passive/pebble_2.yml

Adding properties to support source-type import in MP

---

java-sdk/build.gradle

Is there anything else we should do to prepare a new release of RADAR-Schemas? @blootsvoets

prepare release

---

java-sdk/README.md
java-sdk/build.gradle

0.2.1 release

---

java-sdk/README.md
java-sdk/build.gradle

Updated branch with bumped version

Bump version

---

specifications/stream/android_phone.yml

Added Android phone streams

---

java-sdk/build.gradle
specifications/active/aRMT-1.0.0.yml
specifications/active/aRMT-v1.yml

Release 0.2.3

---

commons/monitor/application/application_time_zone.avsc
specifications/monitor/radar_prmt-1.0.0.yml

Related to RADAR-base/radar-android-application-status#11.

Added application time zone

---

specifications/stream/statistics.yml

change topic name acc to convention source_statistics_producer_model

Change according to topic naming convention

---

java-sdk/README.md
java-sdk/build.gradle

Release 0.3.2

---

commons/active/thincit/thinc_it_pdq.avsc

Remove null from the schemas, Because the thinc it app will never send null values.

Remove null

---

specifications/stream/android_phone.yml

Add output topic to phone usage aggregate stream to fix #117

Add output topic

---

commons/connector/fitbit/fitbit_intraday_heart_rate.avsc
commons/connector/fitbit/fitbit_intraday_steps.avsc
commons/connector/fitbit/fitbit_sleep_pattern.avsc
commons/connector/fitbit/fitbit_sleep_stage.avsc
java-sdk/radar-schemas-commons/src/main/java/org/radarcns/schema/Scope.java
java-sdk/radar-schemas-tools/config/pmd/ruleset.xml
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/CommandLineApp.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/SchemaRegistry.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/DataProducer.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/SourceCatalogue.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/connector/ConnectorDataTopic.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/connector/ConnectorSource.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/stream/StreamDataTopic.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/stream/StreamGroup.java
java-sdk/radar-schemas-tools/src/test/java/org/radarcns/schema/validation/SourceCatalogueValidation.java
specifications/connector/radar-fitbit-connector.yml
specifications/stream/android_phone.yml

- Add skeleton for connector source type
- Add schemas and specifications for fitbit connector
- ~~Add `output_topic` to `StreamDataTopic`~~
- Closes #112 
- @mbegalevibrent this PR will enable to register the topics for fitbit connector but the schemas will need to be registered from the connector. Please see #112

Add Connector specs

---

commons/active/questionnaire/questionnaire_completion_log.avsc
commons/monitor/questionnaire/questionnaire_completion_log.avsc
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/validation/rules/SchemaRules.java
specifications/active/aRMT-1.2.0.yml
specifications/connector/radar-fitbit-connector.yml

Add questionnaire completion log schema and specs

---

java-sdk/radar-schemas-tools/build.gradle

- Closes #124 
- Ref - https://jersey.github.io/release-notes/2.26.html

Add InjectionManager dependency

---

commons/active/questionnaire/questionnaire.avsc
java-sdk/README.md
java-sdk/build.gradle

Some minor fixes - 
- Add question identifier
- Fix catalog server #124

release 0.3.4

---

java-sdk/build.gradle
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/KafkaTopics.java

Hotfix: fix topic registration

Release 0.3.6

---

commons/kafka/record_set.avsc

Can be used for binary transmission to the gateway

Record set

---

specifications/active/aRMT-1.3.0.yml

Fixes https://github.com/RADAR-base/RADAR-Questionnaire/issues/183

Add two more type of questionnaires

---

commons/connector/fitbit/fitbit_activity_log_record.avsc

Activity types are not always reported by Fitbit

Fix optional fitbit activity log type

---

java-sdk/radar-schemas-tools/build.gradle

Updated Jackson and radar-commons

Updated dependencies

---

java-sdk/build.gradle
java-sdk/radar-schemas-tools/build.gradle
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/KafkaTopics.java

Log which bootstrap servers are being used to create topics.

More explicit bootstrap server logging

---

specifications/active/aRMT-1.4.3.yml

- Add audio task 4 to schema spec
- Add audio questionnaires URLs

Add audio task to schema spec

---

specifications/active/aRMT-1.4.3.yml

- Adds app event schema to active app specifications

Add app event schema to specifications

---

commons/connector/fitbit/fitbit_intraday_calories.avsc
specifications/connector/radar-fitbit-connector.yml

- The calories endpoint also includes the activity level and METS.
Required by https://github.com/RADAR-base/RADAR-REST-Connector/issues/25

Fitbit intraday Calories

---

commons/connector/upload/altoida/altoida_eye_tracking.avsc
commons/connector/upload/altoida/altoida_touch.avsc

allow null for eye_tracking
change raw data values to double

allow null for eye_tracking

---

commons/connector/upload/altoida/altoida_summary.avsc
specifications/connector/radar-altoida-connector.yml

move bit and dot metrics and domainresult to separate topics

move bit and dot metrics and domainresult to separate topics

---

commons/connector/upload/axivity/axivity_battery_level.avsc
commons/connector/upload/axivity/axivity_event.avsc
commons/connector/upload/axivity/axivity_metadata.avsc
specifications/connector/radar-axivity-connector.yml

- Corrects axivity schemas and spec

Misc fixes

---

specifications/active/aRMT-1.5.1.yml

- Changes ESM28Q topic name to `questionnaire_esm28q` from `questionnaire_esm`

Modify aRMT ESM topic name

---

specifications/active/banking-app-1.0.0.yml

add specification for banking app schema

add specification for banking app schema

---

java-sdk/README.md
java-sdk/build.gradle

Sync Release 0.5.6

---

commons/connector/upload/physilog/physilog_binary_data.avsc
specifications/connector/radar-physilog-connector-1.0.0.yml

add schemas for physilog binary data reference

Add physilog data schema

---

specifications/active/aRMT-1.5.2.yml
specifications/active/aRMT-1.6.0.yml

- Add COVID-19 questionnaires to aRMT specs (COVID-19 Diagnosis, COVID-19 Symptoms, COVID-19 CNS Baseline, COVID-19 CNS Followup)

Update aRMT specs 

---

java-sdk/build.gradle

Sync Release 0.5.8

---

specifications/active/aRMT-1.6.1.yml

- Adds new questionnaire (CNS_COVID_FOLLOW_UP_V2) to active schema specs

Update aRMT schema specs

---

java-sdk/build.gradle
java-sdk/radar-schemas-tools/build.gradle

Fix Jackson version mismatch error

---

java-sdk/build.gradle

Sync release and bump dev version

Release 0.5.11

---

java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/DataProducer.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/DataTopic.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/stream/StreamDataTopic.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/stream/StreamGroup.java
java-sdk/radar-schemas-tools/src/test/java/org/radarcns/schema/validation/SourceCatalogueValidation.java

Intends to fix #229. Otherwise, the server context may have to be updated to pass an `ObjectMapper` with custom serialisation config.

Ignore stream properties from JSON response

---

Dockerfile
Dockerfile.kafkaInit
README.md
java-sdk/build.gradle
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/CommandLineApp.java
java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/service/SourceCatalogueServer.java
java-sdk/radar-schemas-tools/src/test/java/org/radarcns/schema/service/SourceCatalogueServerTest.java

Changes since version 0.5.11.1:
- Add new questionnaires to aRMT specifications (#237)
- Streamline docker files to be more similar
- Fix help message

Release 0.5.12

---

java-sdk/build.gradle

Sync Release 0.5.12

---

specifications/active/aRMT-1.9.0.yml

New topics:
- questionnaire_epi_seizure_diary
- questionnaire_epi_evening_questionnaire
- questionnaire_epi_wsas

added EPI-specific topics

---

java-sdk/build.gradle

Sync release with dev

---

specifications/active/aRMT-1.11.0.yml

Additional Qs for RALPMH study - 
- VAS (Visual Analog Scale)
- ERS (Exacerbation Rating Scale)

Add VAS and ERS to armt specs

---

java-sdk/build.gradle
java-sdk/gradle/publishing.gradle
java-sdk/radar-schemas-commons/build.gradle
java-sdk/radar-schemas-tools/build.gradle
specifications/active/aRMT-1.11.0.yml

- Fix Maven publication
- Fix Logger in dockerfile
- Add VAS and ERS to aRMTspecs

Release 0.6.1

---

specifications/active/aRMT-1.14.0.yml

- Pulse Ox response
- Unscripted Audio 4 (contains the whole North wind text in a single questionnaire)
- Audio Count
- Audio Vocalisation

Add further questionnaires for RALPMH

---

docker/topic_init.sh
java-sdk/build.gradle
java-sdk/radar-schemas-registration/src/main/java/org/radarbase/schema/registration/KafkaTopics.java
java-sdk/radar-schemas-registration/src/main/java/org/radarbase/schema/registration/TopicRegistrar.java
java-sdk/radar-schemas-tools/src/main/java/org/radarbase/schema/tools/KafkaTopicsCommand.java
java-sdk/radar-schemas-tools/src/main/java/org/radarbase/schema/tools/SubCommand.java

sync dev with latest release: Release 0.7.2 1

---

.github/workflows/main.yml
.github/workflows/release.yml
Dockerfile
docker/list_raw.sh
java-sdk/build.gradle
java-sdk/config/checkstyle/checkstyle.xml
java-sdk/config/pmd/ruleset.xml
java-sdk/gradle/testing.gradle
java-sdk/gradle/wrapper/gradle-wrapper.properties
java-sdk/radar-catalog-server/build.gradle
java-sdk/radar-catalog-server/src/main/java/org/radarbase/schema/service/SourceCatalogueJerseyEnhancer.java
java-sdk/radar-catalog-server/src/main/java/org/radarbase/schema/service/SourceCatalogueServer.java
java-sdk/radar-schemas-core/src/main/java/org/radarbase/schema/specification/DataProducer.java
java-sdk/radar-schemas-core/src/main/java/org/radarbase/schema/specification/SourceCatalogue.java
java-sdk/radar-schemas-core/src/main/java/org/radarbase/schema/specification/active/questionnaire/QuestionnaireDataTopic.java
java-sdk/radar-schemas-core/src/main/java/org/radarbase/schema/validation/SpecificationsValidator.java
java-sdk/radar-schemas-core/src/test/java/org/radarbase/schema/validation/SourceCatalogueValidation.java
java-sdk/radar-schemas-core/src/test/java/org/radarbase/schema/validation/SpecificationsValidatorTest.java
java-sdk/radar-schemas-tools/build.gradle
specifications/passive/carl-cloud-1.0.0.yml

Changes since 0.7.4:
- **Critical**: fixes Log4J CVE-2021-44228 in catalog-server
- Updates other dependencies, including Gradle 7.3 and Java 17
- Adds CANEdge schemas.
- Adds check that specifications can be parsed.

Release 0.7.5

---

specifications/active/aRMT-1.16.0.yml

- Add new questionnaire specs (for `AIMS` study)

Add new aRMT specs

---

commons/connector/fitbit/fitbit_activity_heart_rate.avsc
commons/connector/fitbit/fitbit_intraday_heart_rate.avsc
commons/connector/fitbit/fitbit_sleep_classic.avsc
commons/connector/fitbit/fitbit_sleep_stage.avsc

Reverts RADAR-base/RADAR-Schemas#301

Revert "Add new resource fields restingHeartRate and sleep efficiency"

---

commons/passive/google/google_sleep_segment_event.avsc

Updated schema `google_sleep_segement_event` to have default value of sleep status as null.

Updated default value of sleep segment status to null. 

---

commons/connector/fitbit/fitbit_intraday_spo2.avsc
specifications/connector/radar-fitbit-connector.yml

- Add Fitbit intraday spo2 to schemas and specifications

Add Fitbit oxygen saturation

---

specifications/connector/radar-fitbit-connector.yml

- Add resting HR to Fitbit specs

Add resting HR to Fitbit specs

---

java-sdk/buildSrc/src/main/kotlin/Versions.kt

- Bump to minor release instead of hotfix release

Release 0.8.8

---

.github/workflows/snyk.yaml
java-sdk/buildSrc/src/main/kotlin/Versions.kt

[Security] Fix software vulnerabilities for 0.8.11 release

---

.github/workflows/scheduled_snyk.yaml
.github/workflows/scheduled_snyk_docker.yaml

Add weekly Snyk Docker image scan to Github actions

---

.github/workflows/scheduled_snyk.yaml
.github/workflows/scheduled_snyk_docker.yaml

Fix weekly Snyk Docker image scan

---

.github/workflows/main.yml
.github/workflows/publish-snapshots.yml
.github/workflows/release.yml
.github/workflows/scheduled-snyk-docker.yaml
.github/workflows/scheduled-snyk.yaml
.github/workflows/snyk.yaml
Dockerfile
java-sdk/build.gradle.kts
java-sdk/buildSrc/src/main/kotlin/Versions.kt
java-sdk/gradle/wrapper/gradle-wrapper.properties

This PR will
- Fix and streamline GitHub release and vulnerability scan actions
- Up gradle to 8.13
- Up project version to 0.8.13

release-0.8.13
