Dockerfile, README.md, java-sdk/build.gradle, java-sdk/radar-schemas-tools/build.gradle, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/CommandLineApp.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/service/SourceCatalogueServer.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/service/SourceCatalogueService.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/AppSource.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/DataProducer.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/active/ActiveSource.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/specification/passive/PassiveSource.java, specifications/active/phq8.yml, specifications/active/thincit.yml, specifications/monitor/radar_prmt.yml, specifications/passive/android_phone.yml, specifications/passive/biovotion_vsm1.yml, specifications/passive/empatica_e4.yml, specifications/passive/pebble_2.yml
Introduces catalog server to share source-type specifications provided here. This introduces new properties to uniquely identify a specification version by the combination of vendor, model, version. These three properties are required to create a source-type on ManagementPortal of RADAR.
The catalog server can be run from radar-schema-tools with serve -p <port>
=>  Release 0.2.1

commons/kafka/aggregate_key.avsc, java-sdk/radar-schemas-tools/build.gradle
Use the same JSON guidelines for `time` fields in the aggregate keys as in other objects. This makes a standard MongoDB implementation simpler, as well as the backend code and handling.
=> Harmonize aggregate key

specifications/passive/android_phone-1.0.0.yml, specifications/passive/openweathermap_api-0.1.0.yml
Add specification for the weather API. The weather API provider had a separate vendor/model set. To retroactively enable the weather provider, add a source type `OPENWEATHERMAP`/`API`/`0.1.0` in ManagementPortal.
=> Fix weather api

specifications/active/aRMT-1.4.1.yml
The value of tasks returned is in milliseconds which deviates from all the other times which are in seconds. This needs to be documented.
=> Add additional docs to help data analysts

commons/active/notification/notification.avsc, commons/active/opensmile/open_smile_2_audio_analysis.avsc, commons/active/opensmile/open_smile_2_audio_recording.avsc, specifications/active/aRMT-1.4.2.yml
- The notification schema was exactly same as questionnaire schema. So deprecate it and use the questionnaire schema instead. This also means the `timeNotification` is now added for `notification_thinc_it` topic.
- Added `timeNotification` to audio schemas.
=> add timeNotification to further schemas.

specifications/passive/empatica_e4-1.0.1.yml, specifications/passive/empatica_e4-1.1.0.yml
Added the sensor_status topic to the empatica specification, without it the topic is not created by the radar-schemas-tools and the pRMT app won't send the data (throws unblocking exception).
I put it into a new patch version, wasn't sure if that is OK or if it should just be added to v1.0.0.
=> Empatica spec

commons/passive/phone/phone_relative_location.avsc
Support absolute locations and checks whether the absolute location offset has changed.
An offsetReference int is an arbitrary number that references a static offset. This is randomly generated when the offset is created. Two special cases are encoded: `0` encodes absolute location (no offset) and `null` encodes an unknown reference. Using a null for unknown offset references gives us backwards compatibility with our existing data.
=> Schema support for absolute locations

commons/monitor/application/application_record_counts.avsc
The number of records cached is a bit theoretical (but not entirely out of reach), because it would require about 200 GB of storage. However, at 1000 Hz, recordsSent will exceed integer maximum value after 24 days, which is quite possible.
=> Prevent application status int overflow

specifications/active/aRMT-1.4.3.yml
- Add 2 more audio questionnaire types with the same schema and topic
- Rename PDDS to `patient_determined_disease_step`, PDQ to `perceived_deficits_questionnaire`, and THINC-IT to `THINC_IT` to match protocol questionnaire name and aRMT Definitions folders
- Update audio type to use questionnaire schema
=> Add additional audio types

commons/active/opensmile/open_smile_2_audio_analysis.avsc, commons/active/opensmile/open_smile_2_audio_recording.avsc
Deprecated the Active Audio Schemas because -
1. The active app is not using OpenSmile anymore.
2. The active app is using the generic questionnaire schema for publishing audio records.
=> Deprecated Audio schemas

Dockerfile.kafkaInit, README.md, docker/cc_topic_init.sh, java-sdk/radar-schemas-tools/build.gradle, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/CommandLineApp.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/AbstractTopicRegistrar.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/ConfluentCloudTopics.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/KafkaTopics.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/SchemaRegistry.java, java-sdk/radar-schemas-tools/src/main/java/org/radarcns/schema/registration/TopicRegistrar.java
- Adds a new command to register topics to Confluent Cloud 
- Adds an option to register schemas with authorization, that can be used on Confluent Cloud based Schema registry
- Updates to latest `radar-commons`
=> Option to register topics and schemas to confluent cloud env

Dockerfile.kafkaInit, README.md, docker/init.sh
By setting or overriding `/etc/radar-schemas/specifications.exclude`, a user can exclude certain specifications from being registered by `kafka-init`.
=> Exclude unwanted specifications

commons/connector/upload/altoida/altoida_summary.avsc, commons/connector/upload/altoida/altoida_summary_metrics.avsc
- Make `audioLowReactions` nullable since this is only present in the `DOT` test and not in the `BIT` test
- Remove `groundTruth` since this is not present anymore
=> Update Altoida summary metrics schema

specifications/active/aRMT-1.9.0.yml
- Adds RALPMH questionnaires: cat, psqi, fcfs, fss, ralpmh_covid_symptoms, lipf
- Adds Engage questionnaires: audio_without_unscripted, audio_without_unscripted_2, audio_without_unscripted_3
=> Add RALPMH and Engage study questionnaires to schema specs

docker/topic_init.sh
The starting up of the `radar-schemas-tools` docker image could fail after the "double-checked" topic creation due to unavailable brokers. This PR tries to improve the retry logic.
=> Improve retry on topic creation

commons/connector/fitbit/fitbit_activity_heart_rate.avsc, commons/connector/fitbit/fitbit_intraday_heart_rate.avsc, commons/connector/fitbit/fitbit_sleep_classic.avsc, commons/connector/fitbit/fitbit_sleep_stage.avsc
This PR is related to the issue [#89](https://github.com/RADAR-base/RADAR-REST-Connector/issues/89)
Changes made in the PR:
- Add `restingHeartRate` field to the intraday heart rate schema
- Add `efficiency` field to the sleep classic and stage schemas
=> Add new resource fields restingHeartRate and sleep efficiency

specifications/active/aRMT-1.0.0-general.yml, specifications/active/aRMT-1.17.0.yml
Adds a general `questionnaire_response` Kafka topic to the aRMT app, as well as moving the monitoring topics to that general device type. This allows an installation to have far fewer topics if the users do not require questionnaire responses to be separated over different topics. For example in Confluent Cloud this makes a big cost difference.
=> Add general aRMT topic

commons/active/healthkit/healthkit_typed_data.avsc
- Update `time` field in Healthkit generic schema (change `startTime` to `time`) to fix issues with the filename in output restructure
=> Fix Healthkit schema

commons/passive/google/google_sleep_classify_event.avsc, commons/passive/google/google_sleep_segment_event.avsc, specifications/passive/android_google-1.0.0.yml
Added schemas and specifications required for google sleep api.
=> Schemas added for google sleep APIs

commons/passive/google/google_activity_transition_event.avsc, specifications/passive/android_google_api-1.0.0.yml, specifications/passive/google_activity-1.0.0.yml
Changes:
-  Added `google_activity_recognition_event` schema. 
-  Created specification `android_google_api_1.0.0`, included specifications for activity_transition_events. 
Fixes issue https://github.com/RADAR-base/RADAR-Schemas/issues/337
=> Added schemas for Google activity recognition API.

commons/passive/google/google_activity_transition_event.avsc
During the testing of the activity transition plugin, events for `TILTING` and `UNKNOWN` are not supported. The plugin throws an exception with the message `ActivityTransitionRequest specified an unsupported transition activity type`.
=> removed unsupported activity types from activity transition event

commons/passive/google/google_activity_transition_event.avsc
Updated default value for an activity to null in `google_activity_transition_event.avsc`.
=> Updated default value of activity to null.

commons/passive/phone/phone_bluetooth_device_scanned.avsc
Earlier the pairing state of the remote device is calculated manually, but there is also a straightforward and precise way [here](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#getBondState()).
=> Using PairState enum for paired status of remote bluetooth device.

README.md
It appears that the documents on Confluent Cloud deployment of schemas were not fully updated to reflect the new _radar-schema-tools_ docker image. This PR corrects this.
=> Correct docs on Confluent Cloud deployment

java-sdk/radar-schemas-registration/src/main/java/org/radarbase/schema/registration/SchemaRegistry.kt
During initialization of schema registry the following error was thrown:
```
[2024-03-19 17:47:28,574] INFO  - Initializing SchemaRegistration with authentication... (SchemaRegistryCommand.kt:98)
[2024-03-19 17:47:29,631] ERROR - Schema registry https://psrc-4kk0p.westeurope.azure.confluent.cloud not ready, responded with HTTP 401 Unauthorized: REST call to <https://psrc-4kk0p.westeurope.azure.confluent.cloud/subjects> failed (HTTP code 401 Unauthorized): {"error_code":401,"message":"Unauthorized"} (Emitters.kt:231)
[2024-03-19 17:47:29,633] INFO  - Waiting 1.321031400s seconds to retry (KafkaTopics.kt:303)
```
The cause was that basic authentication headers were not sent during init where the schema registry requests the `/subjects` endpoint.
A basic auth header was added so that the …
=> Fix basic authentication during schema registry init

README.md, java-sdk/buildSrc/src/main/kotlin/Versions.kt
Fix for the confluent cloud issues #369
=> Release 0.8.7-hotfix

java-sdk/build.gradle.kts, java-sdk/buildSrc/src/main/kotlin/Versions.kt, java-sdk/radar-schemas-registration/build.gradle.kts, java-sdk/radar-schemas-registration/src/main/java/org/radarbase/schema/registration/SchemaRegistry.kt, java-sdk/radar-schemas-tools/build.gradle.kts
Issues with basic authentication (see #368)
It seems that httpclient configuration was not properly passed to the `SchemaRegistry`
This PR is dependent on a new release of radar-commons
=> Fix schemaregistry
